### ISSUE TITLE
Investigate timeouts

### ISSUE THREAD

**Issue by mtruj013** [canonical/ubuntu-com-security-api#101]
We are getting random timeouts for the GET endpoints. Typically the problem resolves itself after a few tries/ some time, but we obviously still need to find the reason.

**Comment by ist199099** [comment]
I am also getting 503 Service Unavailable errors frequently and several times in a row.

**Comment by ist199099** [comment]
It happened 4 times in a row at https://ubuntu.com/security/cves?q=&package=unbound&priority=&version=current&status= with Firefox ESR 91.11.0.
