### ISSUE TITLE
Add new `pocket` type `soss`

### ISSUE THREAD

**Issue by albertkol** [canonical/ubuntu-com-security-api#109]
## Summary

Add new `pocket` type `soss`.

**Comment by mossoctopus** [comment]
Hey, I would have an additional request related to this issue. There is one extra bit of information that the team needs in order for our SSNs to be complete, and that would be the `package_type` information (where a `package_type` can be `python`, `conda`, `golang` or `unpackaged`). The ideal thing would be to maybe add a new field into the `NoticePackage` group called `package_type` plus the `soss` pocket type, however, depending on how slower this might be to implement, there is also the possibility of adding 4 more pocket types instead, these pocket types being `soss-python`, `soss-conda`, `soss-golang` and `soss-unpackaged`. This would then change a bit what is being requested here. I was wondering if this is possible and if it is, which case is best to implement?

**Comment by mtruj013** [comment]
Hi @mossoctopus, I believe the first option is fine, when are you looking to have these changes live by?

**Comment by mossoctopus** [comment]
Hey @mtruj013, thanks for the reply. I would most likely need the changes for this week. Is that too soon? :/
