### ISSUE TITLE
Add ROS ESM packages to Ubuntu CVE Tracker website

### ISSUE THREAD

**Issue by florcabral** [canonical/ubuntu-com-security-api#112]
## Summary

Please add ROS ESM packages to Ubuntu CVE Tracker website.

## Process

N/A

## Current and expected result

ROS ESM packages were recently added to UCT (see https://git.launchpad.net/ubuntu-cve-tracker/tree/ros-esm-xenial-kinetic-supported.txt and https://git.launchpad.net/ubuntu-cve-tracker/tree/ros-esm-bionic-melodic-supported.txt). 
Please list these packages in the public UCT website, to publicly reflect any CVEs affecting them.

## Screenshot

N/A

## Browser details

N/A

**Comment by mtruj013** [comment]
Hi @florcabral, sorry I don't quite understand what you're asking for here. Are you requesting a new field be added to the security API? If these are just regular packages the security team should be able to add them to any relevant CVEs and those changes should be automatically reflected on the website.

**Comment by mtruj013** [comment]
Temporary fix for this was added [here](https://github.com/canonical/ubuntu.com/pull/1222), more in depth solution to come pending CVE pages redesign. Closing for now.
