### ISSUE TITLE
The API filter "status" isn't working

### ISSUE THREAD

**Issue by pereyra-m** [canonical/ubuntu-com-security-api#115]
## Summary

When I try to filter the CVEs by status, there is always an error message and the results aren't retrieved.

## Process

All these API calls currently fail

- https://ubuntu.com/security/cves.json?status=active

```JSON
{"errors":"{'query': {'status': {0: ['Cannot find a status with status active']}}}","message":"Invalid payload"}
```

- https://ubuntu.com/security/cves.json?status=rejected

```JSON
{"errors":"{'query': {'status': {0: ['Cannot find a status with status rejected']}}}","message":"Invalid payload"}
```

- https://ubuntu.com/security/cves.json?status=not-in-ubuntu

```JSON
{"errors":"{'query': {'status': {0: ['Cannot find a status with status not-in-ubuntu']}}}","message":"Invalid payload"}
```

## Current and expected result

The API fails to get any result.

It's expected that the filter works properly.
## Browser details

Brave browser: [Versión 1.43.89 Chromium: 105.0.5195.102 (Build oficial) (64 bits)]

**Comment by mtruj013** [comment]
Good catch @pereyra-m, thanks for raising these!

**Comment by pereyra-m** [comment]
Thanks to you !
