### ISSUE TITLE
[Feature request] Add the option to query for multiple CVEs in the query, possibly by specifying multiple ?q=CVE-ID1&q=CVE-ID2

### ISSUE THREAD

**Issue by dparv** [canonical/ubuntu-com-security-api#140]
## Summary

We would like to have the option to query in a single query multiple CVEs (e.g. 10, 20, etc) so we don't have to query the API n-times.

## Process

N/A

## Current and expected result

Be able to query multiple CVEs.

## Screenshot

N/A

## Browser details

N/A

**Comment by samhotep** [comment]
Addressed by https://github.com/canonical/ubuntu-com-security-api/pull/169
