### ISSUE TITLE
security/release endpoints are inconsistent with `support_tag` key

### ISSUE THREAD

**Issue by stevebeattie** [canonical/ubuntu-com-security-api#54]
For the `/security/release` endpoints, when perfoming a GET on a specific release there is a `support_tag` field (as seen in the [swagger doc](https://ubuntu.com/security/api/docs#/default/get_security_releases__release_codename__json); for the current active releases this field contains either the empty string, "LTS", or "ESM", depending on the release. However, I don't see in the swagger documentation a way to add or update this field; it's not mentioned in the swagger API doc for:

- [POSTing an entirely new release](https://ubuntu.com/security/api/docs#/default/post_security_releases_json)
- [PUTting updated information for an existing release](https://ubuntu.com/security/api/docs#/default/put_security_releases__release_codename__json)

The implementation does indeed match the swagger docs, as you can see through queries:

```
$ curl -s -X GET "https://ubuntu.com/security/releases/focal.json" -H "accept: application/json" | jq .
{
  "codename": "focal",
  "development": false,
  "esm_expires": "2030-04-30T00:00:00",
  "lts": true,
  "name": "Focal Fossa",
  "release_date": "2020-04-23T00:00:00",
  "support_expires": "2025-04-30T00:00:00",
  "support_tag": "LTS",
  "version": "20.04"
}
```
and attempts to make a no-change update that includes all fields:
```
# invoking this script with --debug only reports the json to submit and the url it would submit to
$ ./scripts/post-release-to-web-cve-tracker.py --action update focal --debug
PUT https://ubuntu.com/security/releases/focal.json
{
  "name": "Focal Fossa",
  "version": "20.04",
  "codename": "focal",
  "development": false,
  "lts": true,
  "support_tag": "LTS",
  "release_date": "2020-04-23T00:00:00",
  "support_expires": "2025-04-30T00:00:00",
  "esm_expires": "2030-04-30T00:00:00"
}

# the attempt to update the endpoint, which fails
$ ./scripts/post-release-to-web-cve-tracker.py --action update focal 
focal: <Response [422]> {
  "errors": "{'json': {'support_tag': ['Unknown field.']}}",
  "message": "Invalid payload"
}
```
The endpoint will correctly be updated if the `support_tag` key is not included. Is this correct behavior? When it comes time to add 22.04/impish+1, which team is responsible for adding the "LTS" support_tag to the release? Similarly, in April of 2023, what will the process be for changing bionic/18.04's `support_tag` to "ESM"?

Thanks.

**Comment by SirSamTumless** [comment]
@nmav Is this something you can look into?

**Comment by carkod** [comment]
@mtruj013 is this still relevant?

**Comment by 0xDSousa** [comment]
Hello,

With the help of @stevebeattie, an update of a release that had its `support_tag` set as blank was completed.

From the [code](https://github.com/canonical/ubuntu-com-security-api/blob/main/webapp/models.py#L170C6-L177) in the DB model, the `support_tag` field will be derived from the expiration dates and not directly editable.

Therefore, I think that this issue can be closed.

**Comment by stevebeattie** [comment]
Thanks for following up @0xDSousa .
