### ISSUE TITLE
Incorrect CVES addressed value on /16-04

### ISSUE THREAD

**Issue by bethcollins92** [canonical/ubuntu-com-security-api#56]
## Summary

The number of CVE's addressed on https://ubuntu.com/16-04 is 8,142 but it should be around 5941. This number is generated by a query to the API - could there be a bug with the API when it tries to filter the correct CVEs? 

## Screenshot

<img width="1106" alt="Screenshot 2021-10-27 at 15 11 09" src="https://user-images.githubusercontent.com/58959073/139082906-22bf7d87-3963-442d-997a-1beef5127021.png">

**Comment by albertkol** [comment]
@stevebeattie anyone from Security can help us with making sure we get the correct numbers for the https://ubuntu.com/16-04 page?

The query I run against the API to determine the number of CVEs addressed on 16-04 is:
https://ubuntu.com/security/cves.json?version=xenial&status=released&limit=1
In other words: We select the CVEs that have at least one package with the status `released` on the version `xenial`. The number I get at the point in time the number is 8823. Is that incorrect?

**Comment by petesfrench** [comment]
Hi @stevebeattie, could you take a look and confirm whether this return an accurate result for total number of CVE's please: https://ubuntu.com/security/cves.json?version=xenial&status=released&limit=1 it is currently returning 9614
